### ISSUE TITLE
error

### ISSUE THREAD

**Issue by ujrarozu** [Shishkebaboo/VodRecovery#13]
I have installed all modules but i get this error : 
Traceback (most recent call last):

  File "G:\Rtrecover\RecoverVod.py", line 12, in <module>
    from bs4 import BeautifulSoup
ModuleNotFoundError: No module named 'bs4'

also could u please try to revive this vod : https://twitchtracker.com/ms_complicado/streams/40610744232

**Comment by Shishkebaboo** [comment]
Given no further discussion... going to close this issue.
