### ISSUE TITLE
Recovery Problem

### ISSUE THREAD

**Issue by MineClash34** [Shishkebaboo/VodRecovery#14]
Hi!
I want to recover this VOD : https://twitchtracker.com/davidblackhat/streams/48219050701
It's only 7 days old so it seems work but I have tried multiple tools and didn't work
Can you help me? Why it didn't work? The video is recoverable?
Thanks for your answer!

**Comment by Shishkebaboo** [comment]
@MineClash34 

Unfortunately just doesnt exist.
