### ISSUE TITLE
URL as Command Line Arguments

### ISSUE THREAD

**Issue by BrianJ20** [Shishkebaboo/VodRecovery#17]
95% of the time i use the program this way.
```
1) Recover Vod
1) Recover Vod
2) Website Vod Recover
```

So it would be nice if i could simply start the program using

RecoverVod.py -url https://streamscharts.com/channels/streamer/streams/12345678910 
or just 
RecoverVod.py https://streamscharts.com/channels/streamer/streams/12345678910

Am on windows if that matters.

**Comment by Shishkebaboo** [comment]
@BrianJ20 that would take a significant rewrite of the script which I don't have time to complete so for the foreseeable future the script will remain the same.

Closing this issue as if I decide to start a rewrite then I'll open an issue regarding the refactor then at that point in time.
