### ISSUE TITLE
Crashes when parsing a StreamsCharts link

### ISSUE THREAD

**Issue by anga83** [Shishkebaboo/VodRecovery#18]
When I try to do a Website VOD Recover using a link from streamscharts.com, the script crashes with the following message:

```
Traceback (most recent call last):
  File "/Users/xxx/bin/VodRecovery/RecoverVod.py", line 919, in <module>
    run_script()
  File "/Users/xxx/bin/VodRecovery/RecoverVod.py", line 840, in run_script
    website_vod_recover()
  File "/Users/xxx/bin/VodRecovery/RecoverVod.py", line 528, in website_vod_recover
    vod_recover(streamer, vod_id, parse_datetime_streamscharts(tracker_url))
  File "/Users/xxx/bin/VodRecovery/RecoverVod.py", line 458, in vod_recover
    vod_age = get_vod_age(timestamp)
              ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/xxx/bin/VodRecovery/RecoverVod.py", line 159, in get_vod_age
    vod_age = datetime.datetime.today() - format_timestamp(timestamp)
                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/xxx/bin/VodRecovery/RecoverVod.py", line 154, in format_timestamp
    formatted_date = datetime.datetime.strptime(timestamp, datetime_config["DEFAULT_DATETIME_FORMAT"])
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: strptime() argument 1 must be str, not None
```

I can reproduce this with any link, regardless if the VOD would be recoverable or not. Take this as an example: https://streamscharts.com/channels/xqc/streams/42239876827

This problem does not exist for TwitchTracker or SullyGnome.

**Comment by Shishkebaboo** [comment]
@anga83 

Did you change the config file? I am unable to produce the error that your getting... its working fine for me.

https://vod-metro.twitch.tv/08ada484ffed5d3c9e4a_xqc_42239876827_1685214889/chunked/index-dvr.m3u8
Vod contains muted segments
998 of 998 segments are valid (100.00% of the VOD available)

**Comment by anga83** [comment]
Well, I did change the default download directory in the config file. I just double-checked with an uneditted config file and the issue persists.

In the meantime, I digged around myself and may have an explanation, but no I idea why it only affects me.

The error in line 458 is because, `timestamp` is set to "None" instead of a valid timecode. So I took a look why that's the case and ultimately came to point that in this function

```
def parse_datetime_streamscharts(tracker_url):
    for _ in range(10):
        response = requests.get(tracker_url, headers=return_header(), allow_redirects=False)
        if check_response_status_code(response):
            bs = BeautifulSoup(response.content, 'html.parser')
            streamscharts_datetime = bs.find_all('time', {'class': 'ml-2 font-bold'})[0].text.strip().replace(",", "") + ":00"
            return datetime.datetime.strftime(datetime.datetime.strptime(streamscharts_datetime, "%d %b %Y %H:%M:%S"), "%Y-%m-%d %H:%M:%S")
```

I get trapped in the `else` (which does not exist). 

My best guess why the script can't scrape the site's HTML is that Cloudflare security check I have to pass every time I access StreamsCharts. I always thought that may be cause my Chrome does some stupid shit, but they may actually hate all my trafic. (No, I have no clue what it could be. Also by intertent providor changes my IP every day and I can reproduce this regardless of the day.)


So, ultimately, I'm not sure if you can do anything on your end. Just wanted to post this here in case someone else runs into this.

**Comment by Shishkebaboo** [comment]
@anga83 

It's most likely due to the Cloudflare security check as you said but I have no way of getting around that. You can use the manual recovery however for vods that only exist on streamscharts as twitchtracker/sullygnome should suffice for most.

**Comment by Vanwil** [comment]
> When I try to do a Website VOD Recover using a link from streamscharts.com, the script crashes with the following message:
> 
> ```
> Traceback (most recent call last):
>   File "/Users/xxx/bin/VodRecovery/RecoverVod.py", line 919, in <module>
>     run_script()
>   File "/Users/xxx/bin/VodRecovery/RecoverVod.py", line 840, in run_script
>     website_vod_recover()
>   File "/Users/xxx/bin/VodRecovery/RecoverVod.py", line 528, in website_vod_recover
>     vod_recover(streamer, vod_id, parse_datetime_streamscharts(tracker_url))
>   File "/Users/xxx/bin/VodRecovery/RecoverVod.py", line 458, in vod_recover
>     vod_age = get_vod_age(timestamp)
>               ^^^^^^^^^^^^^^^^^^^^^^
>   File "/Users/xxx/bin/VodRecovery/RecoverVod.py", line 159, in get_vod_age
>     vod_age = datetime.datetime.today() - format_timestamp(timestamp)
>                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/Users/xxx/bin/VodRecovery/RecoverVod.py", line 154, in format_timestamp
>     formatted_date = datetime.datetime.strptime(timestamp, datetime_config["DEFAULT_DATETIME_FORMAT"])
>                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> TypeError: strptime() argument 1 must be str, not None
> ```
> 
> I can reproduce this with any link, regardless if the VOD would be recoverable or not. Take this as an example: https://streamscharts.com/channels/xqc/streams/42239876827
> 
> This problem does not exist for TwitchTracker or SullyGnome.

As @Shishkebaboo  said this error is caused by the cloudflare security check and yes, it happens to me too, to avoid it you need a vpn with an ip from a european country (don't ask me why).However, using this configuration works perfectly :)

**Comment by knakamura8** [comment]
Potential integration with https://github.com/VeNoMouS/cloudscraper
