### ISSUE TITLE
VOD Request

### ISSUE THREAD

**Issue by dezii98** [Shishkebaboo/VodRecovery#2]
Can anyone find VOD links to these? I cannot with VodRevovery.

https://streamscharts.com/channels/woohankyung/streams/40060195831
https://streamscharts.com/channels/woohankyung/streams/40062904439

Thanks a lot!

**Comment by Shishkebaboo** [comment]
@dezii98 Neither exist unfortunately. Due to not being able to retrieve a stream that is currently live my guess is the streamer has vod storage disabled.

**Comment by dezii98** [comment]
@Shishkebaboo stream that is currently live work too, I have tested for months. Twitch added a new domain maybe?

**Comment by Shishkebaboo** [comment]
@dezii98 its unlikely.. The streamer in question has 0 past broadcasts, clips, highlights, collections, moments, uploads.

Im running a script currently that checks 1200 streamers for any new domains... I will update this issue if it finds one.

**Comment by dezii98** [comment]
@Shishkebaboo Thank you! I guess I have to record the stream with streamlink now. Twitch has embedded a lot of blank ads with unofficial app
