### ISSUE TITLE
Error message when recovering a VOD. 

### ISSUE THREAD

**Issue by FunkDoctaSpockBrickCity** [Shishkebaboo/VodRecovery#25]
I'm getting this error message when I try to recover a VOD. I followed all of [gameinn1](https://github.com/gameinn1)'s steps. Installed Python, installed the script, installed the recovervod.py folder, renamed it TwitchVOD, added it to my desktop, etc. The videos I'm trying to recover are 1-2 months old and some even recent than that. Any help is much appreciated thank you. 

![Screenshot 2023-07-11 144416](https://github.com/Shishkebaboo/VodRecovery/assets/128324859/741fad91-6f96-4554-a0a6-fb268def2ac0)

**Comment by Shishkebaboo** [comment]
@FunkDoctaSpockBrickCity TwitchTracker is blocking the request, happening on my end as well. I can't really do anything about it... however this behaviour usually goes away within a few hours as its happened multiple times before and works after a couple hours. 

You can either wait like I stated above or you could try using a streamscharts link.
