### ISSUE TITLE
VOD (Website VOD Recover) cannot be found by VodRecovery, but it's there

### ISSUE THREAD

**Issue by SparklingTopaz** [Shishkebaboo/VodRecovery#27]
I had experienced this several times before, and now it has happened to me again. VODs are not found even though they are there.
Here is a fresh example: 
https://twitchtracker.com/mira/streams/42378435259
Now, I always get a message from VodRecovery that the VOD was not found on the server.

There is a quite useful addon for Firefox called "Twitch VOD Downloader and Viewer" https://addons.mozilla.org/de/firefox/addon/andre-bradshaw/?utm_source=addons.mozilla.org&utm_medium=referral&utm_content=search
and this finds the VOD in full length, why does VodRecovery does not the same?

**Comment by Shishkebaboo** [comment]
@ruFdyVDmbkPQnUnr 

It all relies on the start time of the vod which is shown on twitchtracker.. If twitchtracker does not contain the correct timestamp then yes it will return "VOD was not found on the server." as you stated. 

Please use the other websites such as Streamscharts that my script supports... as I believe streamscharts is much more accurate when it comes to  fetching stream information such as start time, duration etc..

**Comment by SparklingTopaz** [comment]
@ Shishkebaboo
thanks for you fast reply, I'll try Streamcharts then.
