### ISSUE TITLE
Unable to unmute segments 

### ISSUE THREAD

**Issue by Ayden3011** [Shishkebaboo/VodRecovery#28]
Hi Shishkebaboo,

I hope you're doing well. I really enjoy using the script; it has been quite helpful to me. Recently, I came across a VOD with muted segments for the first time. The script detected this and asked if I wanted to unmute it. I entered 'Y' and the .m3u8 file was generated. However, the muted segments remained unchanged. I also verified the validity of all segments, and they were indeed valid ("100.00% of the VOD is available"). 

I was wondering if this feature is currently not functioning properly or if it doesn't work with all muted VODs.

Thank you for developing the script.

**Comment by Shishkebaboo** [comment]
@Ayden3011 it does not actually unmute the video. Unmuting refers to modifying the file which then allows the the video to play. If you don't unmute the video will not play at all.

**Comment by Ayden3011** [comment]
Alright, I see. Thank you for your answer. I will close this issue now.
