### ISSUE TITLE
not working today?

### ISSUE THREAD

**Issue by ffedericode** [Shishkebaboo/VodRecovery#29]
Hi, I'm actually trying today with vods that yesterday were present and with new ones but in any case I don't get any answer... not even the typical "No VODS for this stream" line. What is happening? :)
Thank you!

**Comment by Shishkebaboo** [comment]
@ffedericode The script continues to work as expected. I have not made any code changes for quite a while therefore my assumption is that you experienced an anomoly.. my suggestion would be to just try again or try using a different website.
