### ISSUE TITLE
MAJOR REFACTOR - MERGED - February 24th, 2023

### ISSUE THREAD

**Issue by Shishkebaboo** [Shishkebaboo/VodRecovery#3]
A major refactor was just merged into the main branch... these changes alter the way the script will be maintained going forward. 

A json config file is now being used to manage most of the constants that exist in the script as well as redundant user input due to the menu like style  it was originally coded in.

Users can change the config file to match their preferences... I have noted some of the main configuration changes that might be most popular with users in the README.

**Comment by DirtyGodzilla** [comment]
Apologies for bumping this, @Shishkebaboo.

My earlier/above comment had been hidden before the thread was closed. Just wanted to make sure you caught it now that it's visible.

Thanks.

**Comment by Shishkebaboo** [comment]
@DirtyGodzilla If you want to create a new issue outlining what you outlined here.. I can start developing this enhancement.
