### ISSUE TITLE
VOD Recovery process slow & Unable to generate m3u8 file?

### ISSUE THREAD

**Issue by SparklingTopaz** [Shishkebaboo/VodRecovery#32]
For a few weeks now, the VOD recovery has been very slow on my end (even the update to the latest version didn't help).

For example, the recovery of this VOD takes about 7 minutes:  
https://twitchtracker.com/ohnepixel/streams/41028110088

Unfortunately, I have no idea why it suddenly takes so long.
What could be the reason, internet speed and hardware should be ok?

And I am not able to create an m3u8 file from this link in the new version. 
In previous versions, I could enter a twitchtracker link, for example, and it would then generate an m3u8 file for me, which I could optionally unmute.

Currently I can't get this resolved and I can't skip checking the files for invalid segments. I would like to streamline the workflow again (it was easier in the previous versions).
Or am I missing something?
That's what I'm trying to do, but I don't get an m3u8 file:
`1) VOD Recovery
2) Clip Recovery
3) Unmute M3U8 File
4) Verify Segment Availability
5) Create M3U8 File (Comments out invalid segments)
6) Download M3U8 File (.MP4 Extension)
7) Help
8) Exit

Choose an option: 1
1) Single Video Recovery
2) Bulk video Recovery from SullyGnome CSV Export
3) Exit

Select VOD Recovery Mode: 1
1) Manual Recovery
2) Website Video Recovery
3) Exit

Select VOD Recovery Method: 2
Enter Twitchtracker/Streamscharts/Sullygnome url:  https://twitchtracker.com/ohnepixel/streams/41028110088
Searching for videos...
1. chunked
2. 720p60
3. 480p30
Please choose a quality: 1
https://dgeft87wbj63p.cloudfront.net/f8e5f5877139361656a1_ohnepixel_41028110088_1693144502/chunked/index-dvr.m3u8
Video does NOT contain muted segments
Checking segments.. 2197 / 2220
2197 out of 2220 Segments are Available. Please see option 5 of the main menu!
1) VOD Recovery
2) Clip Recovery
3) Unmute M3U8 File
4) Verify Segment Availability
5) Create M3U8 File (Comments out invalid segments)
6) Download M3U8 File (.MP4 Extension)
7) Help
8) Exit

Choose an option: 5
Enter M3U8 Link: https://dgeft87wbj63p.cloudfront.net/f8e5f5877139361656a1_ohnepixel_41028110088_1693144502/chunked/index-dvr.m3u8
Checking segments.. 2220 / 2220
2220 out of 2220 Segments are Available.
1) VOD Recovery
2) Clip Recovery
3) Unmute M3U8 File
4) Verify Segment Availability
5) Create M3U8 File (Comments out invalid segments)
6) Download M3U8 File (.MP4 Extension)
7) Help
8) Exit

Choose an option:`

**Comment by SparklingTopaz** [comment]
Update: Okay I'see that the .m3u8 files do get created but is there any way to skip the checking of the segments?

**Comment by Shishkebaboo** [comment]
@SparklingTopaz The speed in which the script executes is not due to the code. My guess is it has to do with environmental factors such as internet speed, hardware etc.. 

Due to adding qualities to the output the script has to send thousands more HTTP requests to check which ones exist or don't exist. So rather then sending lets say 1,000 requests previously it now has to send 5000-6000 requests. 

In the example you provided.. at first it states that some segments are unavailable but then when you used option 5 all were available... once again this has to do with connection slowness / network latency. 

If its really bad... my suggestion would be to revert back to v1.0.2.0.

**Comment by SparklingTopaz** [comment]
Okay, thank you very much for your quick feedback.
At least the problem has been narrowed down a bit.
It does look like a connection problem, could it be that the Windows Firewall (Windows Defender) is blocking/slowing down the script?

**Comment by Shishkebaboo** [comment]
@SparklingTopaz Change the preferences in the config file.. change the value to False instead of True.

**Comment by SparklingTopaz** [comment]
> Okay, I'll do that, thank you.
