### ISSUE TITLE
last month it was working, now i get these errors 

### ISSUE THREAD

**Issue by rubicon31** [Shishkebaboo/VodRecovery#34]
![Screenshot from 2023-09-15 21-55-10](https://github.com/Shishkebaboo/VodRecovery/assets/106564158/e4a54c0a-8079-402b-9ef6-26d6707b2385)

**Comment by Shishkebaboo** [comment]
@rubicon31 You selected manual recovery then input a link.. Select website recovery and it should work as expected given streamscharts allows the HTTP request to go though.

**Comment by rubicon31** [comment]
> @rubicon31 You selected manual recovery then input a link.. Select website recovery and it should work as expected given streamscharts allows the HTTP request to go though.
![Screenshot from 2023-09-15 22-02-06](https://github.com/Shishkebaboo/VodRecovery/assets/106564158/2aeb523a-ba12-4494-8972-239e8cff90ee)
my bad i had selected the wrong screenshot, i have opened a new one if you dont mind
