### ISSUE TITLE
was working fine last month, now i get these errors

### ISSUE THREAD

**Issue by rubicon31** [Shishkebaboo/VodRecovery#35]
![Screenshot from 2023-09-15 22-02-06](https://github.com/Shishkebaboo/VodRecovery/assets/106564158/9852c3ef-1b6c-43b9-805e-f552f32bde5a)

also my bad for before i had seelcted the wrong screenshot

**Comment by Shishkebaboo** [comment]
@rubicon31 You're on linux therefore the path which is documented in the script to find the config file is not correct.  There was no measures taken in development to identify the users operating system and code based off that.  It was solely coded based off the windows operating system.

**Comment by rubicon31** [comment]
> @rubicon31 You're on linux therefore the path which is documented in the script to find the config file is not correct. There was no measures taken in development to identify the users operating system and code based off that. It was solely coded based off the windows operating system.

![ghj](https://github.com/Shishkebaboo/VodRecovery/assets/106564158/43b4c9ce-03b2-4353-8f44-ec56832d7c2c)
ok, working on windows but doesnt find video
can you check if it does the same on your end 
https://streamscharts.com/channels/frengchiano/streams/40595858519

**Comment by Shishkebaboo** [comment]
@rubicon31 If the script indicates the vod doesnt exist. unfortunately it just doesnt exist... It would not matter as to who ran the script it works the same regardless.
