### ISSUE TITLE
CSV/Bulk Download Returns No VOD Results

### ISSUE THREAD

**Issue by DirtyGodzilla** [Shishkebaboo/VodRecovery#6]
Not sure if this is a bug or a result of my own set-up, but I can't get any results from a bulk search for VODs. Perhaps someone else could attempt a VOD download via CSV and see if the outcome is the same.

I've tried multiple different streamers as well as a variety of time periods (3 days, 1 month, 1 year, etc), and it always returns zero results (even though there should be downloadable VODs). The menu steps taken are: 1-Recover VOD --> 2-Recover VODs from SullyGnome CSV export --> [enter CSV location].

The script processes the VOD IDs as you'd expect it to (there's also network traffic), but every single one returns "No vods found using the current domain list." If I take a SullyGnome link from the same CSV and use it find a single VOD (menu: 1 --> 1 --> 2), it works as it should. Bulk/CSV clip download also works as expected.

I'm on 1.0.0.9.

**Comment by Shishkebaboo** [comment]
@DirtyGodzilla 

It will never work for a year... twitch vod retention policy is max 60 days.

there are a plethora of reasons why it doesn't show results:

1. start time on sullygnome is inaccurate
2. streamer doesn't have vod storage turned on
3. streamer is not a partner or affiliate in which the retention of vods is reduced to 7-14 days depending on which one.

**Comment by DirtyGodzilla** [comment]
> It will never work for a year... twitch vod retention policy is max 60 days.

Not true. There are plenty of partnered streamers that have grandfathered VOD storage of much longer than a year. But really, that was a throwaway comment about how many different variables I've tried in testing out why the bulk download wasn't working.

> there are a plethora of reasons why it doesn't show results:

As I said in the OP, the VODs are there and downloadable (for the half dozen channels I've tried). The links from the CSV work individually. Doing them in a bulk search isn't working. At least it doesn't with how I have things set up, which is why I was requesting someone else test it out (to see if it's a bug or not).

**Comment by Shishkebaboo** [comment]
@DirtyGodzilla  You can't find a past broadcast over a year old that will work in VLC.. you may be able to find the m3u8 but it will not play. I've been developing this since may 2022 and have tested it 100's of times.. I have never found a year old vod that played let alone in full.

I just tried it and it works perfectly.. 

1. Download CSV - do not change the name of the CSV or how the csv is formatted in anyway.
2. Run the application
3. Choose option 1
4. Choose option 2
5. Paste absolute path of CSV file -> "C:\Users\YOUR_USER\Downloads\CSV_FILE"

**Comment by DirtyGodzilla** [comment]
> Download CSV - **_do not change the name of the CSV_** or how the csv is formatted in anyway.

Ahhhh. _There_ it is. I changed the names. That's interesting. I used the same CSVs to bulk download clips, so that process is not affected by the filename change the same way it is for VODs. I didn't consider that one small modification would have that type of impact. The confusing part was how it functioned as it would normally, just without the expected results.

That might be something to note in any future documentation. Or perhaps make it error out. Or somehow allow the CSV filename to be changed.

It also didn't completely solve all the issues I had with bulk/CSV downloads. But since the main problem was due to the CSV _name_, it got me thinking about a couple other bulk attempts that failed. And I think the script isn't handling any CSV filenames with special characters. Particularly Asian lettering. If you attempt to bulk download from Japanese, Chinese, or Korean channels (or any others that use special characters in the display name), the bulk download will output zero results in the same way it does if you change the filename.

> @DirtyGodzilla You can't find a past broadcast over a year old that will work in VLC.. you may be able to find the m3u8 but it will not play. I've been developing this since may 2022 and have tested it 100's of times.. I have never found a year old vod that played let alone in full.... Id challenge you to find one and send me the tracker link that works you will be looking for a long time.

It's not that big of a deal, since it isn't central to this issue here, but I had already downloaded a few VODs that were over a year old prior to making the above post. Thinking that I may have just gotten lucky, or that my method may have been the difference (I _downloaded_ the files via ffmpeg instead of just viewing in VLC), I decided to make a few more attempts.

So I took a scattershot approach and chose 7 random streams (that have existing VODs available on Twitch), from 3 different channels, that date back as far as _two-plus years_. The first two failed. Said something about not being able to resolve the server address or something. But the next five all worked. I downloaded all of them. They all played in VLC.

I then took the m3u8 playlist files and dropped them into VLC. They played with no issue. I went back to the first two failures, because I wanted to see the exact error message they gave, and instead, they both downloaded without a problem (which is why I'm still not exactly sure what the error said).

Here are the tracker URLs for the streams I tested:
https://twitchtracker.com/hasanabi/streams/41454254875
https://twitchtracker.com/jakenbakelive/streams/40806977870
https://twitchtracker.com/jakenbakelive/streams/41666645550
https://twitchtracker.com/jakenbakelive/streams/42738733452
https://twitchtracker.com/jakenbakelive/streams/43014666460
https://twitchtracker.com/pokelawls/streams/42596316525
https://twitchtracker.com/pokelawls/streams/42647924189

**Comment by Shishkebaboo** [comment]
@DirtyGodzilla I'm not sure how jakenbakelive and pokelawls are keeping their vods... maybe they have a contract with twitch I'm honestly not sure. Those are the only two channels I've ever seen with vods from years ago. 

However the vods are not really being recovered as they already exist.. I think my point was more on the side of recovering vods that don't exist when viewing past broadcasts on the twitch website... but either way I stand corrected.

**Comment by DirtyGodzilla** [comment]
@Shishkebaboo

> I'm not sure how jakenbakelive and pokelawls are keeping their vods... maybe they have a contract with twitch

That's exactly how they have old VODs. They're partnered streamers with grandfathered unlimited VOD storage. Jake had nearly every stream for about 6 years saved as VODs but had to delete many when the whole DMCA thing blew up.

Also that Hasan VOD is from 120+ days ago as well.

> Those are the only two channels I've ever seen with vods from years ago that still exist via twitch website.

There are probably more. There are definitely streamers that had the same VOD storage deal, but many of them wiped their _complete library_ over the DMCA fiasco (instead of only the VODs with claims).

> Here is a article on the Korean twitch changes

I'm fully aware of the changes Twitch has made, but that is a whole separate issue that doesn't impact this one.

Korean VOD storage officially ended Feb 7th. Prior to that, VODs were still saved, but after December they couldn't be accessed by anyone from a South Korean IP address (also, clips can _still_ be made by anyone outside of Korea). So there's a remaining month's worth of VODs fully available to watch/download from many partnered Korean streamers ([one example](https://www.twitch.tv/handongsuk/videos?filter=archives&sort=time)), and an untold number of deleted VODs to recover beyond that (especially since many channels recently mass deleted their VODs before Twitch hit the killswitch).

And that doesn't even address those Korean channels that use a streaming server located in a different country (streaming server.. typical for IRL, used to keep from going offline when encountering weak data signals). The stream is sent to a cloud server and then forwarded-on to Twitch, which then allows it to be stored as it normally would, since it isn't coming directly from Korea. Those channels will continue to have VODs available going forward (though still not viewable using a Korean IP).

But again, this isn't the same issue. I tested this on 8-10 random Asian channels (Japanese, Chinese/Taiwanese, and Korean). Any VOD with Asian characters in the SullyGnome CSV filename would not find any results. But use any of the tracker links from within the CSV and they download with no problem. And I can't change the filename to test if the characters are preventing it from working, because that _will also_ cause it not to work.

There were no VOD results for any of the CSVs created from these channels:
https://sullygnome.com/channel/kato_junichi0817/2023/streams
https://sullygnome.com/channel/hanjoudesu/2023/streams
https://sullygnome.com/channel/bbbb87/2023/streams
https://sullygnome.com/channel/kr1stw/2023/streams
https://sullygnome.com/channel/woowakgood/2023/streams
https://sullygnome.com/channel/handongsuk/2023/streams
