### ISSUE TITLE
Can't recover second part of a stream 

### ISSUE THREAD

**Issue by JackRander** [Shishkebaboo/VodRecovery#7]
So, I've been trying to recover the **SECOND PART** of a stream aired not so long ago. 
The **[FIRST PART](https://www.twitch.tv/videos/1740141906)** of the VOD can be found on twitch.

### To summarize:
- Using links from StreamCharts don't work (and it needs o be by StreamCharts);
- Manual VOD Recover doesn't work.

## The StreamCharts Problem

**TwitchTracker** and **SullyGnome** treat both parts as a single stream (with the ID: 47981244509). By using their URLs bellow I do get a '.m3u8' result, but it's just for the FIRST PART.
[TwitchTracker link.](https://twitchtracker.com/thenormiestv/streams/47981244509)
[SullyGnome link.](https://sullygnome.com/channel/thenormiestv/30/stream/47981244509)
**Result:**
https://d1m7jfoe9zdc1j.cloudfront.net/c50bee53cbf2e34ab06d_thenormiestv_47981244509_1676580861/chunked/index-dvr.m3u8

**StreamCharts** does see the stream as 2 parts (**first**: 47981244509 **and second**: 47981244509). But when using ANY StreamCharts URLs I always get an error like shown bellow.
[StreamCharts One.](https://streamscharts.com/channels/thenormiestv/streams/47981244509)
[StreamCharts Two.](https://streamscharts.com/channels/thenormiestv/streams/47981405645)
**Error:**
```
Traceback (most recent call last):
  File "c:\VOD Recovery\RecoverVod.py", line 856, in <module>
    run_script()
  File "c:\VOD Recovery\RecoverVod.py", line 779, in run_script
    website_vod_recover()
  File "c:\VOD Recovery\RecoverVod.py", line 517, in website_vod_recover
    vod_recover(streamer, vod_id, parse_datetime_streamscharts(tracker_url))
  File "c:\VOD Recovery\RecoverVod.py", line 447, in vod_recover
    vod_age = get_vod_age(timestamp)
              ^^^^^^^^^^^^^^^^^^^^^^
  File "c:\VOD Recovery\RecoverVod.py", line 149, in get_vod_age
    vod_age = datetime.datetime.today() - format_timestamp(timestamp)
                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\VOD Recovery\RecoverVod.py", line 144, in format_timestamp
    formatted_date = datetime.datetime.strptime(timestamp, datetime_config["DEFAULT_DATETIME_FORMAT"])
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: strptime() argument 1 must be str, not None
```

## The Manual VOD Recover Problem

Trying to use **Manual VOD Recover** also doesn't work, even when trying to get the **FIRST PART** of the stream, as shown bellow.
```
Enter streamer name: TheNormiesTV
Enter vod id: 47981244509
Enter VOD start time (YYYY-MM-DD HH:MM:SS): 2023-02-16 20:54:00  
``` 
or `2023-02-16 17:54:00` for my timezone (UTC-3), I tried multiple times with both.

**Result:**
```
Vod is 18 day(s) old.

No vods found using the current domain list.
https://sullygnome.com/channel/TheNormiesTV/stream/47981244509
https://twitchtracker.com/TheNormiesTV/streams/47981244509
https://streamscharts.com/channels/TheNormiesTV/streams/47981244509
```
All of these links work by the way... great ;-;...

Maybe it's because I don't know the exact seconds... I don't know... I just want my '.m3u8' of the SECOND PART ;-;

**Comment by Shishkebaboo** [comment]
@JackRander 

here is the second part.

https://d2vjef5jvl6bfs.cloudfront.net/00211c4d64bb401257e5_thenormiestv_47981405645_1676582749/chunked/index-dvr.m3u8
Vod does NOT contain muted segments
627 of 627 Segments are valid

**Comment by JackRander** [comment]
@Shishkebaboo 
Thank you so much. It's working!
Will follow your instructions next time, sorry.

**Comment by Shishkebaboo** [comment]
@JackRander I just latest code which now removes whitespace and changes all input to lowercase... script will work regardless of those minor details now.
