### ISSUE TITLE
Recovery Problem

### ISSUE THREAD

**Issue by kimimaro92** [Shishkebaboo/VodRecovery#9]
Hi Shishkebaboo!

I spent like 2 hours trying to use your tool and others but I didn't succeed to recover a stream I wanted.
Maybe it is not possible for this one, although it is a stream from just 2 days...

Can you tell me if it is really imposible? (and if it is posible it would be super if you can share with me the download link)
https://streamscharts.com/channels/papesan/streams/40136892359

Thanks a lot and great job!

**Comment by Shishkebaboo** [comment]
@kimimaro92 


https://d1mhjrowxxagfy.cloudfront.net/b8a12d1f277a8652ce2e_papesan_40136892359_1678369872/chunked/index-dvr.m3u8
Vod contains muted segments

Attached zipped unmuted file.

[VodRecovery_papesan_40136892359.zip](https://github.com/Shishkebaboo/VodRecovery/files/10951310/VodRecovery_papesan_40136892359.zip)
